project5-voting/Controllers/DebateController.cs
using project5_voting.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace project5_voting.Controllers
{
    public class DebateController : Controller
    {
        ElectionsEntities2 db = new ElectionsEntities2();

        public ActionResult DebateForm()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DebateForm(Debate path)
        {
            path.status = null;

            db.Debates.Add(path);
            db.SaveChanges();
            return RedirectToAction("UserDebate", "Home");
        }
        public ActionResult ShowDebates()
        {
            return View(db.Debates.ToList());
        }

        public ActionResult Show(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Debate uSER = db.Debates.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }

            var checkCandidate1 = db.localCandidates
                .Where(candidate => candidate.national_id == uSER.firstCandidateID)
                .FirstOrDefault();
            var checkCandidate2 = db.localCandidates
                .Where(candidate => candidate.national_id == uSER.secondCandidateID)
                .FirstOrDefault();


            if (checkCandidate1 == null || checkCandidate2 == null)
            {
                ViewBag.CheckID = null;
                ViewBag.ElectionAreia = null;
            }
            else if (checkCandidate1.national_id == uSER.firstCandidateID && checkCandidate2.national_id == uSER.secondCandidateID)
            {
                ViewBag.CheckID = true;

                if (checkCandidate1.election_area == uSER.electionArea && checkCandidate2.election_area == uSER.electionArea)
                {
                    ViewBag.ElectionAreia = true;
                }
                else
                {
                    ViewBag.ElectionAreia = null;
                }
            }

            return View(uSER);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Show(Debate path)
        {
            if (ModelState.IsValid)
            {
                db.Entry(path).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ShowDebates");
            }


            return View(path);
        }

    }


}

project5-voting/Controllers/HomeController.cs
using project5_voting.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace project5_voting.Controllers
{
    public class HomeController : Controller
    {

        ElectionsEntities2 db = new ElectionsEntities2();

        public ActionResult Index()
        {

            return View();
        }

        public ActionResult SelectList()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult ploice() { 

            return View();
        }

       

        public ActionResult VotersDetails()
        {
            var voter = TempData["voterDetails"] as string;

            if (!string.IsNullOrEmpty(voter))
            {
                var checkInputs = db.USERS.Where(model => model.NationalID == voter).FirstOrDefault();

                if (checkInputs != null)
                {
                    ViewBag.Error = true;
                    return View(checkInputs);
                }
                else
                {
                    ViewBag.Error = false;
                }
            }

            return View();
        }

        public ActionResult Search(string Search)
        {
            if (!string.IsNullOrEmpty(Search))
            {
                TempData["voterDetails"] = Search;
            }

            return RedirectToAction("VotersDetails");
        }

     
        public ActionResult Application()
        {
            return View(); 
        }


        public ActionResult UserDebate()
        {
            var debateCards = db.Debates.Where(model => model.status == 1).ToList();

            return View(debateCards);
        }


        public ActionResult Logout()
        {
            HttpCookie existingCookie = Request.Cookies["logedInUser"];
            HttpCookie existingCookie1 = Request.Cookies["electionArea"];

            existingCookie.Expires = DateTime.Now.AddDays(-1);
            existingCookie1.Expires = DateTime.Now.AddDays(-1);

            Response.Cookies.Set(existingCookie);
            Response.Cookies.Set(existingCookie1);

            return RedirectToAction("Index", "Home");
        }


        public ActionResult RequestForm()
        {
            return View();
        }

    }
}

project5-voting/Controllers/partyController.cs
using MimeKit;
using project5_voting.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MailKit.Net.Smtp;
using Microsoft.Ajax.Utilities;
using MimeKit;
using System.Net;

namespace project5_voting.Controllers
{
    public class partyController : Controller
    {
        ElectionsEntities2 db = new ElectionsEntities2();

        public ActionResult Createuser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Createuser([Bind(Include = "id,partyName,counter")] partyList partyList)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var existingParty = db.partyLists.FirstOrDefault(p => p.partyName == partyList.partyName);

                    db.partyLists.Add(partyList);
                    db.SaveChanges();
                    Session["PartyId"] = partyList.id;
                    Session["PartyName"] = partyList.partyName;
                    Session["Counter"] = 0;

                    return RedirectToAction("Create"); // تأكد من صحة اسم الـ Controller والإجراء
                }
                catch (DbEntityValidationException ex)
                {
                    // Print the details to the error log or console
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            ModelState.AddModelError(validationError.PropertyName, validationError.ErrorMessage);
                        }
                    }
                }
            }

            return View(partyList);

        }

        //////////////////////////////// ADD Candidite///////////////////////////////////////
      
        public ActionResult SetStatus(long id, string status)
        {
            var partyName = Session["PartyName"] as string;

            // البحث عن المرشح باستخدام المعرف
            var candidate = db.partyCandidates.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }

            // تحديث حالة المرشح
            candidate.status = status;
            db.Entry(candidate).State = EntityState.Modified;
            db.SaveChanges();

            // التحقق مما إذا كان هناك أي مرشح في نفس الحزب لديه حالة "0"
            var partyId = candidate.partyId;
            var hasRejectedCandidates = db.partyCandidates.Any(c => c.partyId == partyId && c.status == "0");

            if (hasRejectedCandidates)
            {
                var party = db.partyLists.Find(partyId);
                if (party != null)
                {
                    // تحديث حالة الحزب إلى "0" إذا كان هناك مرشح مرفوض
                    party.status = "0";
                    db.Entry(party).State = EntityState.Modified;
                    db.SaveChanges();

                    try
                    {
                        SendEmail("انت مرفوض في تقديم", "election2024jordan@gmail.com");
                        ViewBag.Message = "Email sent successfully.";
                        ViewBag.PartyName = partyName;
                        return RedirectToAction("AdminView", new { partyName = partyName });
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "An unexpected error occurred. Please try again later.";
                        Console.WriteLine("Exception message: " + ex.Message);
                        Console.WriteLine("Stack trace: " + ex.StackTrace);
                    }
                }
            }
            else
            {
                // إذا كانت جميع المرشحين في نفس الحزب لديهم حالة "1"، تأكد من تحديث حالة الحزب
                var allCandidatesAccepted = db.partyCandidates.Where(c => c.partyId == partyId).All(c => c.status == "1");
                if (allCandidatesAccepted)
                {
                    var party = db.partyLists.Find(partyId);
                    if (party != null)
                    {
                        party.status = "1"; // حالة الحزب إلى "مقبول" إذا كان جميع المرشحين مقبولين
                        db.Entry(party).State = EntityState.Modified;
                        db.SaveChanges();

                        try
                        {
                            SendEmail("تم الموافقه على طلبك", "election2024jordan@gmail.com");
                            ViewBag.Message = "Email sent successfully.";
                            ViewBag.PartyName = partyName;
                            return RedirectToAction("AdminView", new { partyName = partyName });
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Message = "An unexpected error occurred. Please try again later.";
                            Console.WriteLine("Exception message: " + ex.Message);
                            Console.WriteLine("Stack trace: " + ex.StackTrace);
                        }
                    }
                }
            }

            return RedirectToAction("AdminView", new { partyName = partyName });
        }


        private void SendEmail(string messageText, string toEmail)
        {
            string fromEmail = "ayahaldomi@gmail.com";
            string fromName = "test";
            string subjectText = "نتيجتك في طلب تقديم";

            string smtpServer = "smtp.gmail.com";
            int smtpPort = 465; // Port 465 for SSL

            string smtpUsername = "election2024jordan@gmail.com";
            string smtpPassword = "zwht jwiz ivfr viyt"; // Ensure this is correct

            var message = new MimeMessage();
            message.From.Add(new MailboxAddress(fromName, fromEmail));
            message.To.Add(new MailboxAddress("", toEmail));
            message.Subject = subjectText;
            message.Body = new TextPart("plain") { Text = messageText };

            using (var client = new SmtpClient())
            {
                client.Connect(smtpServer, smtpPort, true); // Use SSL
                client.Authenticate(smtpUsername, smtpPassword);
                client.Send(message);
                client.Disconnect(true);
            }
        }


        [HttpPost]
        public JsonResult StorePartyNameInSession(string partyName)
        {
            Session["PartyName"] = partyName;
            return Json(new { success = true });
        }


        public ActionResult AdminView(string partyName)
        {
            if (string.IsNullOrEmpty(partyName))
            {
                partyName = Session["PartyName"] as string;
            }
            else
            {
                Session["PartyName"] = partyName;
            }

            if (string.IsNullOrEmpty(partyName))
            {
                // التعامل مع الحالة عندما لا يكون partyName مخزن في الجلسة
                return RedirectToAction("Index", "PartyList"); // أو أي عرض آخر
            }

            var candidates = db.partyCandidates.Where(pc => pc.partyList.partyName == partyName).ToList();
            ViewBag.PartyName = partyName;
            return View(candidates);
        }


        [HttpGet]
        public ActionResult SearchUser(string nationalIdSearch)
        {
            if (string.IsNullOrEmpty(nationalIdSearch))
            {
                ViewBag.ErrorMessage = "Please enter a National ID.";
                return View("Create");
            }

            var user = db.USERS.FirstOrDefault(u => u.NationalID == nationalIdSearch);

            if (user == null)
            {
                ViewBag.ErrorMessage = "No user found with the provided National ID.";
                return View("Create");
            }

            var partyCandidate = new partyCandidate
            {
                email = user.email,
                name = user.name,
                nationalId = user.NationalID,
                gender = user.gender,
                birthDay = user.birth_date,
            };

            ViewBag.partyId = new SelectList(db.partyLists, "id", "partyName");
            return View("Create", partyCandidate);
        }

        public ActionResult index()
        {
            var id = Session["PartyId"] as string;
            var partyName = Session["PartyName"] as string;
            var counter = Session["Counter"] as int?;

            if (string.IsNullOrEmpty(partyName) || counter == null)
            {
                TempData["ErrorMessage"] = "Session values are missing. Redirecting to Createuser.";
                return RedirectToAction("Createuser", "partyLists");
            }

            var partyList = db.partyLists.FirstOrDefault(p => p.partyName == partyName);
            if (partyList == null)
            {
                TempData["ErrorMessage"] = "Party not found.";
                return RedirectToAction("Createuser", "partyLists");
            }

            int parsedPartyId;
            if (partyList.id > int.MaxValue)
            {
                TempData["ErrorMessage"] = "Party ID is too large.";
                return RedirectToAction("Createuser", "partyLists");
            }
            else
            {
                parsedPartyId = (int)partyList.id;
            }

            var partyCandidates = db.partyCandidates
                .Where(p => p.partyId == parsedPartyId)
                .Include(p => p.partyList)
                .ToList();

            if (!partyCandidates.Any())
            {
                ViewBag.ErrorMessage = "No candidates found for the selected party.";
            }

            ViewBag.PartyId = parsedPartyId;
            ViewBag.PartyName = partyName;
            ViewBag.Counter = counter;
            ViewBag.Id = id;

project5-voting/Views/Home/Application.cshtml
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<style>
    .card-hover {
        transition: transform 0.3s, box-shadow 0.3s;
        border: 3px solid #ff0000; /* Red border for cards */
    }

        .card-hover:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
        }

    .card-body {
        background-color: #ffffff; /* White background for card body */
        color: #000000; /* Black text for better contrast */
    }

    .card-title {
        color: #ff0000; /* Red title text */
        font-size: 1.5rem;
        font-weight: bold;
    }

    .card-text {
        color: #008000; /* Green text for card descriptions */
        font-size: 1.1rem;
    }

    .card-img-top {
        border-bottom: 2px solid #ff0000; /* Red border for images */
    }

    .btn-custom {
        background-color: #008000; /* Green button background */
        border-color: #008000; /* Green button border */
        color: #ffffff; /* White text */
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 1.1rem;
    }

        .btn-custom:hover {
            background-color: #006400; /* Darker green on hover */
            border-color: #006400;
            color: #ffffff;
        }
</style>

<div class="container mt-4">
    <h1 class="text-center">القوائم المحلية و الحزبية</h1>
    <div class="row">
        <!-- بطاقة قائمة الحزب -->
        <div class="col-md-6 mb-4">
            <div class="card card-hover text-decoration-none text-black" style="height: 400px; width: 100%; max-width: 600px;">
                <img src="~/images/1حزبي.png" class="card-img-top" alt="قائمة الحزب" style="height: 300px; object-fit: cover;" />
                <div class="card-body bg-light text-danger rounded-bottom d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title">قائمة الحزبية</h5>
                    <p class="card-text">
                        عند ضغط هنا سوف تتجه لإنشاء القائمة الحزبية من أجل الترشح للانتخابات.
                    </p>
                    <a href="@Url.Action("Createuser", "partyLists")" class="btn btn-custom">اذهب لبناء للقائمة</a>
                </div>
            </div>
        </div>

        <!-- بطاقة القائمة المحلية -->
        <div class="col-md-6 mb-4">
            <div class="card card-hover text-decoration-none text-black" style="height: 400px; width: 100%; max-width: 600px;">

                <img src="~/images/محلي.png" class="card-img-top" alt="القائمة المحلية" style="height: 300px; object-fit: cover;" />
                <div class="card-body bg-light text-danger rounded-bottom d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title">القائمة المحلية</h5>
                    <p class="card-text">
                        عند ضغط هنا سوف تتجه لإنشاء القائمة المحلية من أجل الترشح للانتخابات.
                    </p>
                    <a href="@Url.Action("", "")" class="btn btn-custom">اذهب لبناء للقائمة</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

project5-voting/Views/Home/RequestForm.cshtml
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<style>
    .card-hover {
        transition: transform 0.3s, box-shadow 0.3s;
        border: 3px solid #ff0000; /* Red border for cards */
    }

        .card-hover:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
        }

    .card-body {
        background-color: #ffffff; /* White background for card body */
        color: #000000; /* Black text for better contrast */
    }

    .card-title {
        color: #ff0000; /* Red title text */
        font-size: 1.5rem;
        font-weight: bold;
    }

    .card-text {
        color: #008000; /* Green text for card descriptions */
        font-size: 1.1rem;
    }

    .card-img-top {
        border-bottom: 2px solid #ff0000; /* Red border for images */
    }

    .btn-custom {
        background-color: #008000; /* Green button background */
        border-color: #008000; /* Green button border */
        color: #ffffff; /* White text */
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 1.1rem;
    }

        .btn-custom:hover {
            background-color: #006400; /* Darker green on hover */
            border-color: #006400;
            color: #ffffff;
        }
</style>

<div class="container mt-4">
    <h1 class="text-center">القوائم المحلية و الحزبية</h1>
    <div class="row">
        <!-- بطاقة قائمة الحزب -->
        <div class="col-md-6 mb-4">
            <div class="card card-hover text-decoration-none text-black" style="height: 400px; width: 100%; max-width: 600px;">
                <img src="~/images/1حزبي.png" class="card-img-top" alt="قائمة الحزب" style="height: 300px; object-fit: cover;" />
                <div class="card-body bg-light text-danger rounded-bottom d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title">قائمة الحزبية</h5>
                    <p class="card-text">
                        عند ضغط هنا سوف تتجه لإنشاء القائمة الحزبية من أجل الترشح للانتخابات.
                    </p>
                    <a href="@Url.Action("Createuser", "party")" class="btn btn-custom">اذهب لبناء للقائمة</a>
                </div>
            </div>
        </div>

        <!-- بطاقة القائمة المحلية -->
        <div class="col-md-6 mb-4">
            <div class="card card-hover text-decoration-none text-black" style="height: 400px; width: 100%; max-width: 600px;">

                <img src="~/images/محلي.png" class="card-img-top" alt="القائمة المحلية" style="height: 300px; object-fit: cover;" />
                <div class="card-body bg-light text-danger rounded-bottom d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title">القائمة المحلية</h5>
                    <p class="card-text">
                        عند ضغط هنا سوف تتجه لإنشاء القائمة المحلية من أجل الترشح للانتخابات.
                    </p>
                    <a href="@Url.Action("localList", "localCandidates")" class="btn btn-custom">اذهب لبناء للقائمة</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

project5-voting/Views/Home/SelectList.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main class="container mt-4">
    <div class="row">
        <!-- بطاقة قائمة الحزب -->
        <div class="col-md-6 mb-4">
            <a href="@Url.Action("Createuser", "party")" class="card card-hover text-decoration-none text-black" style="height: 400px; width: 100%; max-width: 600px;">
                <img src="~/images/القائمه الحزبيه2.png" class="card-img-top" alt="قائمة الحزب" style="height: 300px; object-fit: cover; border-bottom: 2px solid #003366;" />
                <div class="card-body bg-dark text-light rounded-bottom d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title">قائمة الحزب</h5>
                    <p class="card-text">
                        عند ضغط هنا سوف تتجه لإنشاء القائمة الحزبية من أجل الترشح للانتخابات.
                    </p>
                </div>
            </a>
        </div>

        <!-- بطاقة القائمة المحلية -->
        <div class="col-md-6 mb-4">
            <a href="@Url.Action("", "")" class="card card-hover text-decoration-none text-black" style="height: 400px; width: 100%; max-width: 600px;">
                <img src="~/images/القائمة المحلية.png" class="card-img-top" alt="القائمة المحلية" style="height: 300px; object-fit: cover; border-bottom: 2px solid #003366;" />
                <div class="card-body bg-dark text-light rounded-bottom d-flex flex-column justify-content-center align-items-center">
                    <h5 class="card-title">القائمة المحلية</h5>
                    <p class="card-text">
                        عند ضغط هنا سوف تتجه لإنشاء القائمة المحلية من أجل الترشح للانتخابات.
                    </p>
                </div>
            </a>
        </div>
    </div>
</main>

<style>
    .card-hover {
        transition: transform 0.3s, box-shadow 0.3s;
        border: 2px solid #003366; /* Navy Blue border for cards */
    }

        .card-hover:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
        }

    .card-body {
        background-color: #003f6c; /* Darker navy blue for card background */
        color: #ffffff; /* White text for better contrast */
    }

    .card-title {
        color: #ffffff; /* White title text */
    }

    .card-text {
        color: #cce0ff; /* Light blue text for card descriptions */
    }

    .card-img-top {
        border-bottom: 2px solid #003366; /* Navy Blue border for images */
    }
</style>

project5-voting/Views/Home/UserDebate.cshtml
@model IEnumerable<project5_voting.Models.Debate>

@{
    ViewBag.Title = "UserDebate";
}

<h2 class="text-center">المناظرات</h2>

<div class="container mt-4" dir="rtl">
    <div class="row">
        @foreach (var debate in Model)
        {
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h5>تفاصيل المناظرة</h5>
                    </div>
                    <div class="card-body">
                        <dl class="row">
                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.electionArea)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.electionArea)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.firstCandidate)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.firstCandidate)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.firstCandidateID)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.firstCandidateID)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.firstCandidateList)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.firstCandidateList)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.secondCandidate)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.secondCandidate)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.secondCandidateID)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.secondCandidateID)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.secondCandidateList)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.secondCandidateList)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.subject)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.subject)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.message)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.message)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.zoomLink)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.zoomLink)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.status)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.status)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.date)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.date)</dd>
                            </div>

                            <div class="col-sm-5">
                                <dt>@Html.DisplayNameFor(model => model.time)</dt>
                            </div>
                            <div class="col-sm-7">
                                <dd>@Html.DisplayFor(model => debate.time)</dd>
                            </div>
                        </dl>
                        <a href="@Url.Action("DebateForm", "Debate")" class="btn btn-secondary btn-animate">قدم طلب للمناظرة</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>