project5-voting/Controllers/AdsController.cs
using project5_voting.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace project5_voting.Controllers
{
    public class AdsController : Controller
    {
           
        private ElectionsEntities2 db = new ElectionsEntities2();

        private readonly string PayPalBaseUrl = "https://api.sandbox.paypal.com/";
        private readonly string ClientId = "ARPUvF-CVZ4yA8o3ZTmyxU_9aw2AJZYjW8pDJ09OXyPNPy9aZYNPxSdc-ZCBpF8YT64dnwh6EEfXEZo5";
        private readonly string Secret = "EGQ1yUiAMYaL706LnAuZ7Iw6iP9EY055w16japE4OxnTvCbZ8INxSm7pq5TN1twjyirDkRSZo-GqA4-T";
        // GET: Ads
        public ActionResult advertisementAdmin()
        {
            return View(db.Ads.ToList());
        }

        // GET: Ads/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // GET: Ads/Create
        public ActionResult addAdvertisement()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> addAdvertisement([Bind(Include = "id,nationalId,data,listId,partyName,electionArea,description,status")] Ad ad, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(upload.FileName);

                    var path = Path.Combine(Server.MapPath("~/Images/"), fileName);


                    if (!Directory.Exists(Server.MapPath("~/Images/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Images/"));
                    }

                    ad.status = "معلق";
                    upload.SaveAs(path);
                    ad.URL = fileName;
                }
                db.Ads.Add(ad);
                db.SaveChanges();

            }
            try
            {
                var accessToken = await GetAccessToken1();

                var paymentPayload = new
                {
                    intent = "sale",
                    payer = new
                    {
                        payment_method = "paypal"
                    },
                    transactions = new[]
                    {
                        new
                        {
                            amount = new
                            {
                                total = "300",
                                currency = "USD"
                            },
                            description = "Payment description"
                        }
                    },
                    redirect_urls = new
                    {
                        return_url = "https://example.com/returnUrl",
                        cancel_url = "https://example.com/cancelUrl"
                    }
                };

                var paymentJson = Newtonsoft.Json.JsonConvert.SerializeObject(paymentPayload);

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(PayPalBaseUrl);
                    client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);
                    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                    var content = new StringContent(paymentJson, Encoding.UTF8, "application/json");

                    var response = await client.PostAsync("/v1/payments/payment", content);

                    if (response.IsSuccessStatusCode)
                    {
                        var responseContent = await response.Content.ReadAsStringAsync();
                        var responseObject = Newtonsoft.Json.JsonConvert.DeserializeObject<dynamic>(responseContent);

                        string approvalUrl = null;
                        var linksArray = responseObject.links as Newtonsoft.Json.Linq.JArray;
                        if (linksArray != null)
                        {
                            var approvalLink = linksArray.FirstOrDefault(l => (string)l["rel"] == "approval_url");
                            if (approvalLink != null)
                            {
                                approvalUrl = approvalLink["href"].ToString();
                            }
                        }

                        if (!string.IsNullOrEmpty(approvalUrl))
                        {
                            return Redirect(approvalUrl);
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Approval URL not found in PayPal response.";
                            return View("Error");
                        }
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Failed to initiate PayPal payment: " + response.ReasonPhrase;
                        return View("Error");
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An error occurred: " + ex.Message;
                return View("Error");
            }
        }

        public ActionResult Publish(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }

            // Update the status of the ad to published
            ad.status = "تم نشر الاعلان";
            db.Entry(ad).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("advertisementAdmin");
        }

        public ActionResult Publishs()
        {
            // إرجاع جميع الإعلانات من قاعدة البيانات
            var ads = db.Ads.ToList();
            return View(ads);
        }


        // GET: Ads/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // POST: Ads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nationalId,data,listId,partyName,electionArea,description,URL,status")] Ad ad, HttpPostedFileBase upload)
        {
            if (upload != null && upload.ContentLength > 0)
            {
                var fileName = Path.GetFileName(upload.FileName);

                var path = Path.Combine(Server.MapPath("~/Images/"), fileName);


                if (!Directory.Exists(Server.MapPath("~/Images/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Images/"));
                }


                upload.SaveAs(path);
                ad.URL = fileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(ad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("advertisementAdmin");
            }
            return View(ad);
        }

        // GET: Ads/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = db.Ads.Find(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            return View(ad);
        }

        // POST: Ads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Ad ad = db.Ads.Find(id);
            db.Ads.Remove(ad);
            db.SaveChanges();
            return RedirectToAction("advertisementAdmin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }








        //paymnt


        public async Task<ActionResult> Checkout()
        {
            try
            {
                var accessToken = await GetAccessToken();

                var paymentPayload = new
                {
                    intent = "sale",
                    payer = new
                    {
                        payment_method = "paypal"
                    },
                    transactions = new[]
                    {
                        new
                        {
                            amount = new
                            {
                                total = "130.1",
                                currency = "USD"
                            },
                            description = "Payment description"
                        }
                    },
                    redirect_urls = new
                    {
                        return_url = "https://example.com/returnUrl",

project5-voting/Controllers/DebateController.cs
using project5_voting.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace project5_voting.Controllers
{
    public class DebateController : Controller
    {
        ElectionsEntities2 db = new ElectionsEntities2();

        public ActionResult DebateForm()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DebateForm(Debate path)
        {
            path.status = null;

            db.Debates.Add(path);
            db.SaveChanges();
            return RedirectToAction("UserDebate", "Home");
        }
        public ActionResult ShowDebates()
        {
            return View(db.Debates.ToList());
        }

        public ActionResult Show(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Debate uSER = db.Debates.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }

            var checkCandidate1 = db.localCandidates
                .Where(candidate => candidate.national_id == uSER.firstCandidateID)
                .FirstOrDefault();
            var checkCandidate2 = db.localCandidates
                .Where(candidate => candidate.national_id == uSER.secondCandidateID)
                .FirstOrDefault();


            if (checkCandidate1 == null || checkCandidate2 == null)
            {
                ViewBag.CheckID = null;
                ViewBag.ElectionAreia = null;
            }
            else if (checkCandidate1.national_id == uSER.firstCandidateID && checkCandidate2.national_id == uSER.secondCandidateID)
            {
                ViewBag.CheckID = true;

                if (checkCandidate1.election_area == uSER.electionArea && checkCandidate2.election_area == uSER.electionArea)
                {
                    ViewBag.ElectionAreia = true;
                }
                else
                {
                    ViewBag.ElectionAreia = null;
                }
            }

            return View(uSER);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Show(Debate path)
        {
            if (ModelState.IsValid)
            {
                db.Entry(path).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ShowDebates");
            }


            return View(path);
        }

    }


}

project5-voting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">

    <style>
        .btn-secondary {
            color: #ffff;
            background-color: forestgreen;
            border-color: forestgreen;
        }
    </style>
</head>

<body>
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5" style="direction: rtl;">
        <a href="@Url.Action("Index", "Home")" class="navbar-brand d-flex align-items-center">
            <h1 class="m-0">الانتخابات الأردنية</h1>
        </a>
        <button type="button" class="navbar-toggler ms-0" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="d-flex align-items-center w-100">
                <div class="navbar-nav mx-auto p-4 p-lg-0">

                    <a href="@Url.Action("Index", "Home")" class="nav-item nav-link active">الرئيسية</a>
                    <a href="@Url.Action("About", "Home")" class="nav-item nav-link">عنا</a>

                    <ul class="navbar-nav">
                        <!-- Dropdown Menu -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                حملات
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("Publishs", "Ads")">الحملات الانتخابية</a>
                                <a class="dropdown-item" href="@Url.Action("addAdvertisement", "Ads")">لنشر حملتك</a>
                            </div>
                        </li>
                    </ul>

                    <a href="@Url.Action("ploice", "Home")" class="nav-item nav-link">سياساتنا</a>

                    <a href="@Url.Action("localANDparty", "ElectionArea")" class="nav-item nav-link">الدوائر الانتخابية</a>
                    <a href="@Url.Action("VotersDetails", "Home")" class="nav-item nav-link">اين تنتخب</a>

                    @{
                        HttpCookie startDateTimeCookie = Request.Cookies["startDateTime"];
                        HttpCookie endDateTimeCookie = Request.Cookies["endDateTime"];

                        if (startDateTimeCookie == null || endDateTimeCookie == null)
                        {
                            startDateTimeCookie = new HttpCookie("startDateTime", "0000000");
                            Response.Cookies.Add(startDateTimeCookie);

                            endDateTimeCookie = new HttpCookie("endDateTime", "0000000");
                            Response.Cookies.Add(endDateTimeCookie);
                        }



                        var startdate = Request.Cookies["startDateTime"].Value;
                        var endate = Request.Cookies["endDateTime"].Value;

                        var date = DateTime.Now.ToString();

                        int result1 = string.Compare(startdate, date);
                        int result2 = string.Compare(endate, date);


                        if (result1 < 0 && result2 < 0)
                        {
                            <a href="@Url.Action("Result", "Result")" class="nav-item nav-link">النتائج</a>
                        }
                        else if (result1 > 0 && result2 > 0)
                        {
                            <a href="@Url.Action("Application", "Home")" class="nav-item nav-link">طلب الترشح</a>
                        }


                        <a href="@Url.Action("UserDebate", "Home")" class="nav-item nav-link">مناظرات</a>
                        <a href="@Url.Action("Contact", "Contacts")" class="nav-item nav-link">اتصل بنا</a>



                        HttpCookie existingCookie = Request.Cookies["logedInUser"];
                        if (existingCookie == null)
                        {
                            <a href="@Url.Action("firststeplogin", "Login")" class="nav-item nav-link ms-3">تسجيل الدخول</a>
                        }
                        else
                        {
                            <a href="@Url.Action("Logout", "Login")" class="nav-item nav-link ms-3">تسجيل الخروج</a>

                        }


                    }
                </div>
            </div>
        </div>
    </nav>


    <!-- Navbar End -->
    <main>
        @RenderBody()
    </main>

    <!-- Footer Start -->
    <div class="container-fluid bg-dark footer mt-5 py-5 wow fadeIn" data-wow-delay="0.1s" style="direction: rtl;">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">الانتخابات الأردنية</h5>
                    <p>موقع خاص بتنظيم عملية الانتخاب. ويسهل عملية الانتخاب في جميع أنحاء المملكة الأردنية الهاشمية.</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">مكتبنا</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>الأردن، عمان</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+962 7700 0000</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@gmail.com</p>
                    <div class="d-flex pt-3">
                        <a class="btn btn-square btn-secondary rounded-circle me-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-secondary rounded-circle me-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-secondary rounded-circle me-2" href="#"><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square btn-secondary rounded-circle me-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">روابط سريعة</h5>
                    <a class="btn btn-link" href="@Url.Action("About", "Home")">من نحن</a>
                    <a class="btn btn-link" href="@Url.Action("Contact", "Home")">اتصل بنا</a>
                    <a class="btn btn-link" href="@Url.Action("Service", "Home")">خدماتنا</a>
                    <a class="btn btn-link" href="#">الشروط والأحكام</a>
                    <a class="btn btn-link" href="#">الدعم</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">موقعنا</h5>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387190.2799026342!2d-74.2598756877944!3d40.69767006777951!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c250b06d9d8f91%3A0xc80b8f06e177fe62!2sNew+York%2C+USA!5e0!3m2!1sen!2s!4v1550463278013" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>




    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>
    <script src="~/lib/parallax/parallax.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>


    <script src="~/js/main.js"></script>
</body>
</html>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

project5-voting/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.all.min.js"></script>

    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f8f9fa; /* Light background color */
        }

        .nav-link {
            color: #ffffff; /* White color for the nav links */
        }

        .sidebar {
            background-color: #001f3f; /* Navy color for the sidebar */
            min-height: 100vh; /* Full viewport height */
        }

        .sidebar-header {
            background-color: #004080; /* Darker navy color */
            color: #ffffff; /* White text color */
            padding: 20px;
            text-align: center;
        }

            .sidebar-header h4 {
                margin-bottom: 0;
            }

        .content {
            background-color: #ffffff; /* White background for content */
            min-height: 100vh; /* Ensure content takes full height */
            padding: 20px;
        }

        .nav-item {
            border-bottom: 1px solid #004080; /* Darker navy border for separation */
        }

        .nav-link:hover {
            background-color: #0055a5; /* Lighter navy background on hover */
            color: #ffffff; /* White text on hover */
        }

        .user-wrapper img {
            border: 3px solid #ffffff; /* White border around the profile picture */
            margin-bottom: 10px;
        }

        .user-wrapper h4,
        .user-wrapper small {
            color: #ffffff; /* White text for user information */
        }

        .logout-btn {
            position: absolute;
            bottom: 20px;
            width: 100%;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="d-flex flex-column flex-md-row">
        <nav class="sidebar d-flex flex-column p-3 w-80 w-md-auto mb-3 mb-md-0">
            <div class="sidebar-header">
                <div class="user-wrapper d-flex flex-column align-items-center">
                    <img src="~/images/instructor8.jpg" alt="User" class="rounded-circle" style="width: 100px; height: 100px;" />
                    <div class="text-center">
                        <h4>@Session["Admin"]</h4>
                        <small>Super admin</small>
                    </div>
                </div>
            </div>
            <ul class="nav flex-column mt-3">
                <li class="nav-item">
                    @Html.ActionLink("طلبات الترشح", "IndexAdmin", "party", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("طلبات المناظره", "ShowDebates", "Debate", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("طلبات الاعلانات", "advertisementAdmin", "Ads", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("تواصل", "AdminContact", "Contacts", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("معلومات الناخب", "", "", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("تاريخ البدايه والنهاية", "AddDateAndTime", "DateAndTimes", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("نتائج الانتخابات", "", "", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("اضافة ادمن", "addAdmain", "AddAdmin", new { area = "" }, new { @class = "nav-link" })
                </li>

                <li class="nav-item">
                    <br />
                    @Html.ActionLink("تسجيل الخروج", "Logout", "Login", new { area = "" }, new { @class = "btn btn-danger" })
                </li>
            </ul>
        </nav>

        <div class="content flex-grow-1">
            @RenderBody()
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>