project5-voting/Models/localCandidate.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localCandidate
    {
        public long id { get; set; }
        public string candidateName { get; set; }
        public string election_area { get; set; }
        public string email { get; set; }
        public string national_id { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birth_day { get; set; }
        public string religion { get; set; }
        public string typeOfChair { get; set; }
        public string listName { get; set; }
        public Nullable<long> counter { get; set; }
        public string img { get; set; }
        public Nullable<long> listKey { get; set; }
    
        public virtual localList localList { get; set; }
    }
    public class LocalCandidatesGroupedViewModel
    {
        public string ListName { get; set; }
        public List<localCandidate> Candidates { get; set; }
    }
}

project5-voting/Models/localList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5_voting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public localList()
        {
            this.localCandidates = new HashSet<localCandidate>();
        }
    
        public long id { get; set; }
        public string listName { get; set; }
        public string electionDistrict { get; set; }
        public Nullable<long> counter { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<localCandidate> localCandidates { get; set; }
    }

   
}

project5-voting/Controllers/localCandidatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using project5_voting.Models;

namespace project5_voting.Controllers
{
    public class localCandidatesController : Controller
    {
        private ElectionsEntities2 db = new ElectionsEntities2();
        public ActionResult localList()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult localList(localList localList)
        {
            localList.counter = 0;
            localList.status = "0";
            db.localLists.Add(localList);
            db.SaveChanges();

            Session["listName"] = localList.listName;
            Session["listId"] = localList.id;
            Session["electionArea"] = localList.electionDistrict;

            return RedirectToAction("localCandidate");
        }

        public ActionResult ClearSessionAndRedirect()
        {
            // Clear session data
            Session["listName"] = null;
            Session["listId"] = null;
            Session["electionArea"] = null;

            // Redirect to the Index action of the Home controller
            return RedirectToAction("Index", "Home");
        }

        // GET: localCandidates
        public ActionResult localCandidate()
        {
            Session["wrongId"] = "";

            var localCandidates = db.localCandidates.ToList();
            return View(localCandidates);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult localCandidate(localCandidate localCandidate)
        {
            var candidate = db.USERS.FirstOrDefault(u => u.NationalID == localCandidate.national_id);
            if (candidate == null)
            {
                Session["wrongId"] = "You entered a wrong national ID.";
                return RedirectToAction("localCandidate");
            }

            localCandidate.listName = Session["listName"].ToString();
            localCandidate.candidateName = candidate.name;
            localCandidate.election_area = Session["electionArea"].ToString();
            localCandidate.email = candidate.email;
            localCandidate.gender = candidate.gender;
            localCandidate.birth_day = candidate.birth_date;
            localCandidate.religion = candidate.religion;
            localCandidate.counter = 0;
            localCandidate.listKey = Convert.ToInt64(Session["listId"]);
            db.localCandidates.Add(localCandidate);
            db.SaveChanges();
            return RedirectToAction("localCandidate");
        }

        public ActionResult locaListAdmin()
        {
            return View(db.localLists.ToList());
        }
       
        public ActionResult localCandidateAdmin(long? id)
        {
            Session["listIdAdmin"] = id;
            var selectedList = db.localLists.FirstOrDefault(u => u.id == id);
            if (selectedList == null)
            {
                return HttpNotFound();
            }

            string electionArea = selectedList.electionDistrict;
            var localCandidates = db.localCandidates
                .Where(c => c.listKey == id)
                .ToList();

            if (electionArea == "اربد الاولى")
            {
                bool allOver25 = localCandidates.All(c =>
                    c.birth_day.HasValue && (DateTime.Now.Year - c.birth_day.Value.Year) > 25);

                bool hasType1Chair = localCandidates.Any(c => c.typeOfChair == "كوتا");
                bool hasAtLeast8Candidates = localCandidates.Count >= 8;

                if (allOver25 && hasType1Chair && hasAtLeast8Candidates)
                {
                    selectedList.status = "1";
                    db.Entry(selectedList).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            if (electionArea == "اربد الثانية")
            {
                bool allOver25 = localCandidates.All(c =>
                    c.birth_day.HasValue && (DateTime.Now.Year - c.birth_day.Value.Year) > 25);

                bool hasType1ChairWoman = localCandidates.Any(c => c.typeOfChair == "كوتا");
                bool hasType1Chairchristian = localCandidates.Any(c => c.typeOfChair == "مسيحي");
                bool hasAtLeast8Candidates = localCandidates.Count >= 7;

                if (allOver25 && hasType1ChairWoman && hasAtLeast8Candidates && hasType1Chairchristian)
                {
                    selectedList.status = "1";
                    db.Entry(selectedList).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            if (electionArea == "mafraq")
            {
                bool allOver25 = localCandidates.All(c =>
                    c.birth_day.HasValue && (DateTime.Now.Year - c.birth_day.Value.Year) > 25);

                bool hasType1ChairWoman = localCandidates.Any(c => c.typeOfChair == "كوتا");
                bool hasAtLeast8Candidates = localCandidates.Count >= 4;

                if (allOver25 && hasType1ChairWoman && hasAtLeast8Candidates)
                {
                    selectedList.status = "1";
                    db.Entry(selectedList).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            Session["selectedList"] = selectedList.status;

            var localCandidate = db.localCandidates.ToList();
            return View(localCandidate);
        }

        // GET: localCandidates/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            localCandidate localCandidate = db.localCandidates.Find(id);
            if (localCandidate == null)
            {
                return HttpNotFound();
            }
            return View(localCandidate);
        }

        // GET: localCandidates/Create
        public ActionResult Create()
        {
            ViewBag.listKey = new SelectList(db.localLists, "id", "listName");
            return View();
        }

        // POST: localCandidates/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,candidateName,election_area,email,national_id,gender,birth_day,religion,typeOfChair,listName,counter,listKey,img")] localCandidate localCandidate)
        {
            if (ModelState.IsValid)
            {
                db.localCandidates.Add(localCandidate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.listKey = new SelectList(db.localLists, "id", "listName", localCandidate.listKey);
            return View(localCandidate);
        }

        // GET: localCandidates/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            localCandidate localCandidate = db.localCandidates.Find(id);
            if (localCandidate == null)
            {
                return HttpNotFound();
            }
            ViewBag.listKey = new SelectList(db.localLists, "id", "listName", localCandidate.listKey);
            return View(localCandidate);
        }

        // POST: localCandidates/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,candidateName,election_area,email,national_id,gender,birth_day,religion,typeOfChair,listName,counter,listKey")] localCandidate localCandidate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(localCandidate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.listKey = new SelectList(db.localLists, "id", "listName", localCandidate.listKey);
            return View(localCandidate);
        }

        // GET: localCandidates/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            localList localList = db.localLists.Find(id);
            if (localList == null)
            {
                return HttpNotFound();
            }
            return View(localList);
        }

        // POST: localCandidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            localList localList = db.localLists.Find(id);
            if (localList != null)
            {
                db.localLists.Remove(localList);
                db.SaveChanges();
            }
            return RedirectToAction("locaListAdmin");
        }
    }
}

project5-voting/Views/localCandidates/locaListAdmin.cshtml
@model IEnumerable<project5_voting.Models.localList>


@{
    ViewBag.Title = "locaListAdmin";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";

}

<h2 class="text-center">طلبات الترشح للقوائم المحلية</h2>



<div class="card" dir="rtl" style="margin: 20px auto; text-align:right">
    <div class="card-body">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.listName)</th>
                    <th>@Html.DisplayNameFor(model => model.electionDistrict)</th>
                    <th>@Html.DisplayNameFor(model => model.status)</th>
                    <th>الإجراءات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.listName)</td>
                        <td>@Html.DisplayFor(modelItem => item.electionDistrict)</td>
                        <td>
                            @if (item.status == null)
                            {
                                <span class="badge badge-warning">معلق</span>
                            }
                            else if (item.status == "0")
                            {
                                <span class="badge badge-danger">مرفوض</span>
                            }
                            else
                            {
                                <span class="badge badge-success">مقبول</span>
                            }
                        </td>
                        <td>
                            @Html.ActionLink("التفاصيل", "localCandidateAdmin", new { id = item.id }, new { @class = "btn btn-info btn-sm" })
                            @using (Html.BeginForm("Delete", "localLists", FormMethod.Post, new { id = "delete-form-" + item.id }))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('هل أنت متأكد أنك تريد حذف هذا العنصر؟')">حذف</button>
                                @Html.Hidden("id", item.id)
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

project5-voting/Views/localCandidates/localCandidate.cshtml
@model IEnumerable<project5_voting.Models.localCandidate>


<style>
    body {
        direction: rtl;
    }

    .text-right {
        text-align: right;
    }

    .text-left {
        text-align: left;
    }

    .form-horizontal .form-group {
        text-align: right;
    }

    .form-group.row {
        direction: rtl;
    }

    .card {
        border-width: 2px; /* Makes the border thicker for better visibility */
    }
</style>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-right">تقدم طلب أسماء المترشحين</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container mt-4">
        <div class="card border-dark shadow-sm">
            <div class="card-body">
                <h4 class="card-title text-right text-dark">تعبئة أسماء المترشحين في القائمة</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group row">
                    <label class="control-label col-md-2 text-right">الرقم الوطني</label>
                    <div class="col-md-10">
                        <input name="national_id" class="form-control" />
                        <span class="text-danger">@ViewBag.error</span>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="control-label col-md-2 text-right">نوع المقعد</label>
                    <div class="col-md-10">
                        <select name="typeOfChair">
                            <option value="">اختر  نوع مقعد الترشح</option>
                            <option value="تنافس">تنافس</option>
                            <option value="كوتا">كوتا</option>
                            <option value="مسيحي">مسيحي</option>

                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-md-2">
                        <input type="submit" value="إنشاء" class="btn btn-dark" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="container mt-4">
    <div class="card border-dark shadow-sm">
        <div class="card-body">
            <table class="table table-bordered table-striped text-right">
                <thead>
                    <tr>
                        <th>الرقم</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().candidateName)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().election_area)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().email)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().national_id)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().gender)</th>
                        <th>تاريخ الميلاد</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().religion)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().typeOfChair)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().listName)</th>
                        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().localList.listName)</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        int counter = 1;
                        foreach (var item in Model)
                        {
                            if (Convert.ToInt64(Session["listId"]) == item.listKey)
                            {
                                <tr>
                                    <td>@counter</td>
                                    <td>@Html.DisplayFor(modelItem => item.candidateName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.election_area)</td>
                                    <td>@Html.DisplayFor(modelItem => item.email)</td>
                                    <td>@Html.DisplayFor(modelItem => item.national_id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.gender)</td>
                                    <td>@item.birth_day.Value.ToString("yyyy-MM-dd")</td>
                                    <td>@Html.DisplayFor(modelItem => item.religion)</td>
                                    <td>@Html.DisplayFor(modelItem => item.typeOfChair)</td>
                                    <td>@Html.DisplayFor(modelItem => item.listName)</td>
                                    <td>@Html.DisplayFor(modelItem => item.localList.listName)</td>
                                    <td>@Html.ActionLink("حذف", "Delete", new { id = item.id }, new { @class = "btn btn-danger btn-sm" })</td>
                                </tr>
                                counter++;
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="container mt-4">
    <a href="javascript:void(0);" class="btn btn-secondary" onclick="confirmBackToHome()">تقديم الطلب</a>
</div>

@{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        function confirmBackToHome() {
            Swal.fire({
                title: 'هل أنت متأكد من تقديم الطلب؟',

                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'نعم، انتقل!',
                cancelButtonText: 'لا، ابقى هنا'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '@Url.Action("ClearSessionAndRedirect", "localCandidates")';
                }
            });
        }
    </script>
}

project5-voting/Views/localCandidates/localCandidateAdmin.cshtml
@model IEnumerable < project5_voting.Models.localCandidate>

@{
    ViewBag.Title = "localCandidateAdmin";
}

<h2>localCandidateAdmin</h2>
@if (Session["selectedList"] == "1")
{
    <button id="approve" class="btn btn-primary">Check</button>
}
else
{
    <button id="showAlert" class="btn btn-primary">Check</button>
}



<table class="table">
    <thead>
        <tr>
            <th>Counter</th>
            <th>
اسم المرشح            </th>
            <th>
الدائرة الانتخابية            </th>
            <th>
البريد الالكتروني            </th>
            <th>
الرقم الوطني            </th>
            <th>
الجنس            </th>
            <th>
                Birth Day
            </th>
            <th>
الديانة            </th>
            <th>
المقعد الانتخابي            </th>
            <th>
اسم القائمة            </th>


        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            int counter = 1;
            foreach (var item in Model)
            {
                if (Convert.ToInt64(Session["listIdAdmin"]) == item.listKey)
                {
                    <tr>
                        <td>
                            @counter
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.candidateName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.election_area)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.national_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.gender)
                        </td>
                        <td>
                            @item.birth_day.Value.ToString("yyyy-MM-dd")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.religion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.typeOfChair)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.listName)
                        </td>
                    </tr>
                    counter++;
                }
            }
        }
    </tbody>
</table>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.getElementById('showAlert').addEventListener('click', function () {
        Swal.fire({
            icon: 'error',
            title: 'Denied',
            text: 'Something went wrong!',

        });
    });
    document.getElementById('approve').addEventListener('click', function () {
        Swal.fire({
            icon: 'success',
            title: 'Approved',
            text: 'All Good!',

        });
    });
</script>

project5-voting/Views/localCandidates/localList.cshtml
@model project5_voting.Models.localList



<h2 class="text-right mb-4">طلب الترشح للقوائم المحلية</h2>

@Html.AntiForgeryToken()
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container mt-5">
        <div class="card border-dark shadow-lg">
            <div class="card-body">
                <h4 class="card-title text-right text-dark mb-4">تعبئة طلب الترشح</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-horizontal">
                    <div class="form-group row mb-3">
                        <label class="col-md-2 col-form-label text-dark text-right">اسم القائمة</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.listName, new { htmlAttributes = new { @class = "form-control", placeholder = "الرجاء ادخال اسم القائمة", style = "color: #495057;" } })
                            @Html.ValidationMessageFor(model => model.listName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        <label class="col-md-2 col-form-label text-dark text-right">اسم الدائرة</label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(
                                model => model.electionDistrict,
                                new SelectList(
                                    new List<SelectListItem>
                                    {
                                        new SelectListItem { Value = "", Text = "اختر دائرة" },
                                        new SelectListItem { Value = "Circle 1", Text = "اربد الاولى" },
                                        new SelectListItem { Value = "Circle 2", Text = "اربد الثانية" },
                                        new SelectListItem { Value = "Circle 3", Text = "المفرق" }
                                    },
                                    "Value",
                                    "Text"),
                                new { @class = "form-control", required = "required" }
                            )
                            @Html.ValidationMessageFor(model => model.electionDistrict, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-10 offset-md-2">
                            <button type="submit" style="background-color:black " class="btn btn-primary btn-lg">تقديم</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container mt-3">
        @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-secondary" })
    </div>
}

@{
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    body {
        direction: rtl;
    }

    .text-right {
        text-align: right;
    }

    .text-left {
        text-align: left;
    }

    .form-horizontal .form-group {
        text-align: right;
    }

    .form-group.row {
        direction: rtl;
    }

    .card {
        border-width: 2px; /* Makes the border thicker for better visibility */
    }
</style>